DELETE FROM `monstertype` WHERE `id` = 70060;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(70060, '', 70060, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90148;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90148, '', 90148, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90313;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90313, '', 90313, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90328;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90328, '', 90328, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90329;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90329, '', 90329, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90330;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90330, '', 90330, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90331;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90331, '', 90331, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 90332;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(90332, '', 90332, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 91101;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(91101, '', 91101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 91106;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(91106, '', 91106, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 1438300;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(1438300, '', 1438300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 1442200;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(1442200, '', 1442200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
DELETE FROM `monstertype` WHERE `id` = 1442300;
INSERT INTO `monstertype` (`id`, `name`, `sort`, `drop_money_min`, `drop_money_max`, `is_money_share`, `is_map_awardmoney`, `award_exp`, `ishare`, `ismapaward_exp`, `camp`, `additive_attribute`, `pve_energy`) VALUES
(1442300, '', 1442300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
